name: "cargo-deb-arm"
description: "Executes cargo deb for a specified ARM target."
branding:
  icon: box
  color: "red"
inputs:
  args:
    description: "Arguments to pass to cargo deb"
    required: true
    default: "--target=aarch64-unknown-linux-gnu"
  working-directory:
    description: "The working directory. Relative to the repo."
    required: true
    default: "./"
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.args }}
    - ${{ inputs.working-directory }}
