FROM rust:slim-buster

RUN dpkg --add-architecture armhf
RUN apt-get update

RUN apt-get install -qy dpkg-dev
RUN apt-get install -qy g++-arm-linux-gnueabihf libc6-dev-armhf-cross binutils-arm-linux-gnueabihf

RUN rustup target add armv7-unknown-linux-gnueabihf

RUN mkdir -p ~/.cargo/
RUN touch ~/.cargo/config
RUN echo "[target.armv7-unknown-linux-gnueabihf]\nobjcopy = { path = \"arm-linux-gnueabihf-objcopy\" }\nstrip = { path = \"arm-linux-gnueabihf-strip\" }" > ~/.cargo/config

RUN cargo install cargo-deb --version 1.38.0 --locked

ENV CARGO_TARGET_ARMV7_UNKNOWN_LINUX_GNUEABIHF_LINKER=arm-linux-gnueabihf-gcc \
    CC_arm_unknown_linux_gnueabihf=arm-linux-gnueabihf-gcc \
    CXX_arm_unknown_linux_gnueabihf=arm-linux-gnueabihf-g++

WORKDIR /volume
COPY entry.sh /entry.sh
ENTRYPOINT ["/entry.sh"]