# Publishes the image.

name: publish

on:
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  publish:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        tuple:
          - { name: "cargo-deb-arm", filePath: "Dockerfile" }
          - {
              name: "cargo-deb-aarch64-unknown-linux-gnu",
              filePath: "docker/Dockerfile.aarch64-unknown-linux-gnu",
            }
          - {
              name: "cargo-deb-armv7-unknown-linux-gnueabihf",
              filePath: "docker/Dockerfile.armv7-unknown-linux-gnueabihf",
            }
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get Docker image metadata
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          tags: "latest"
          images: ${{ env.REGISTRY }}/${{ matrix.tuple.name }}

      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          file: ${{ matrix.tuple.filePath }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
