# Publishes the image.

name: "Publish"

on:
  workflow_dispatch:
  workflow_call:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  publish:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        tuple:
          - { name: "clementtsang/cargo-deb-arm", filePath: "Dockerfile" }
          - {
              name: "clementtsang/cargo-deb-aarch64-unknown-linux-gnu",
              filePath: "docker/Dockerfile.aarch64-unknown-linux-gnu",
            }
          - {
              name: "clementtsang/cargo-deb-armv7-unknown-linux-gnueabihf",
              filePath: "docker/Dockerfile.armv7-unknown-linux-gnueabihf",
            }
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get Docker image metadata
        id: meta
        uses: docker/metadata-action@57396166ad8aefe6098280995947635806a0e6ea
        with:
          images: ${{ env.REGISTRY }}/${{ matrix.tuple.name }}
          labels: |
            org.opencontainers.image.description=A Docker container for cross-compilation with cargo deb on ARM.
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=sha

      - name: Log in to the Container registry
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@c56af957549030174b10d6867f20e78cfd7debc5
        with:
          context: .
          file: ${{ matrix.tuple.filePath }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
