# A simple test to test the functionality the action.

name: test

on:
  pull_request:
  workflow_dispatch:
  workflow_call:
  push:
    branches: [master]

jobs:
  dockerfile-simple:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        triple:
          - {
              filePath: "Dockerfile",
              arch: "aarch64-unknown-linux-gnu",
              dpkg: "arm64",
            }
          - {
              filePath: "docker/Dockerfile.aarch64-unknown-linux-gnu",
              arch: "aarch64-unknown-linux-gnu",
              dpkg: "arm64",
            }
          - {
              filePath: "docker/Dockerfile.armv7-unknown-linux-gnueabihf",
              arch: "armv7-unknown-linux-gnueabihf",
              dpkg: "armhf",
            }
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build Dockerfile
        run: |
          docker build -t test -f ${{ matrix.triple.filePath }} .

      - name: Run Dockerfile
        run: |
          docker run -t --rm --mount type=bind,source="$(pwd)",target=/volume test "--target ${{ matrix.triple.arch }}" "/volume/test/hello_world"

      - name: Check dpkg information
        run: |
          cd test/hello_world
          cp ./target/${{ matrix.triple.arch }}/debian/hello_world_*.deb ./hello_world.deb
          dpkg -I hello_world.deb | grep ${{ matrix.triple.dpkg }} && echo "Found correct architecture"

  action-no-build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        tuple:
          - { arch: "aarch64-unknown-linux-gnu", dpkg: "arm64" }
          - { arch: "armv7-unknown-linux-gnueabihf", dpkg: "armhf" }
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install toolchain
        uses: actions-rs/toolchain@88dc2356392166efad76775c878094f4e83ff746 # https://github.com/actions-rs/toolchain/commit/88dc2356392166efad76775c878094f4e83ff746
        with:
          profile: minimal
          toolchain: stable
          override: true
          target: ${{ matrix.tuple.arch }}

      - uses: Swatinem/rust-cache@cb2cf0cc7c5198d3364b9630e2c3d457f160790c # 1.4.0
        with:
          cache-on-failure: true
          working-directory: test/hello_world

      - name: Build
        run: |
          cd test/hello_world
          cargo install cross
          cross build --release --verbose --target ${{ matrix.tuple.arch }}

      - name: Run cargo deb
        uses: ./
        with:
          args: --no-build --target ${{ matrix.tuple.arch }}
          working-directory: test/hello_world

      - name: Check dpkg information
        run: |
          cd test/hello_world
          cp ./target/${{ matrix.tuple.arch }}/debian/hello_world_*.deb ./hello_world.deb
          dpkg -I hello_world.deb | grep ${{ matrix.tuple.dpkg }} && echo "Found correct architecture"

  action-build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        tuple:
          - { arch: "aarch64-unknown-linux-gnu", dpkg: "arm64" }
          - { arch: "armv7-unknown-linux-gnueabihf", dpkg: "armhf" }
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run cargo deb
        uses: ./
        with:
          args: --target ${{ matrix.tuple.arch }}
          working-directory: test/hello_world

      - name: Check dpkg information
        run: |
          cd test/hello_world
          cp ./target/${{ matrix.tuple.arch }}/debian/hello_world_*.deb ./hello_world.deb
          dpkg -I hello_world.deb | grep ${{ matrix.tuple.dpkg }} && echo "Found correct architecture"
