# Regularly checks for updates to the base image.

name: update

on:
  schedule:
    - cron: "0 23 * * *"
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  check-update:
    runs-on: ubuntu-latest
    outputs:
      needs_update: ${{ steps.base_update_check.outputs.needs-updating }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Docker Image Update Checker
        id: base_update_check
        uses: lucacome/docker-image-update-checker@v1.1.0
        with:
          base-image: rust:slim-buster
          image: clementtsang/cargo-deb-arm

  update:
    needs: check-update
    if: ${{ needs.check-update.outputs.needs_update == 'true' }}
    uses: ./.github/workflows/publish.yml
