# Regularly checks for updates to the base image.

name: "Update"

on:
  schedule:
    - cron: "0 23 * * *"
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  check-update:
    runs-on: ubuntu-latest
    outputs:
      needs_update: ${{ steps.base_update_check.outputs.needs-updating }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Check if the base image is updated (note this updates all images)
        id: base_update_check
        uses: giggio/docker-image-update-checker@5be041c50dbfdcd5b81a0d4590f14f8c9bbf2cec
        with:
          base-image: rust:slim-buster
          image: ghcr.io/clementtsang/cargo-deb-arm

  test:
    needs: check-update
    if: ${{ needs.check-update.outputs.needs_update == 'true' }}
    uses: ./.github/workflows/test.yml

  update:
    needs: [test, check-update]
    if: ${{ needs.check-update.outputs.needs_update == 'true' }}
    uses: ./.github/workflows/publish.yml
