# Regularly checks for updates to the base image.

name: "Update"

on:
  schedule:
    - cron: "0 23 * * *"
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  check-update:
    runs-on: ubuntu-latest
    outputs:
      needs_update: ${{ steps.base_update_check.outputs.needs-updating }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run
        id: run
        uses: ClementTsang/docker-check-base-image-diff@v0.0.1-alpha
        with:
          base-image: docker://rust:slim-buster
          derived-image: docker://ghcr.io/clementtsang/cargo-deb-arm

  test:
    needs: check-update
    if: ${{ needs.check-update.outputs.differs == 'true' }}
    uses: ./.github/workflows/test.yml

  update:
    needs: [test, check-update]
    if: ${{ needs.check-update.outputs.differs == 'true' }}
    uses: ./.github/workflows/publish.yml
